---
abstract: 'show where calls to a named subroutine are compiled'
author:
  - 'Written by Mark Fowler B<mark@twoshortplanks.com>.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder::Tester: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-CompiledCalls
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  B::CallChecker: 0.000
  B::Compiling: 0.02
  perl: 5.8.0
resources:
  homepage: http://github.com/2shortplanks/Devel-CompiledCalls/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/2shortplanks/Devel-CompiledCalls.git
version: 1.00
